Box-drawing_character & Block_Elements
sindresorhus/is-fullwidth-code-point pull request #1
Opened 2017-01-08 04:41 UTC by bluelovers

+			// https://en.wikipedia.org/wiki/Box-drawing_character
+			(0x2500 <= x && x <= 0x257f) ||
+			// https://en.wikipedia.org/wiki/Block_Elements
+			(0x2580 <= x && x <= 0x259f) ||

2017-01-08 10:28 UTC, sindresorhus commented
Don't do unrelated changes.

2017-01-08 18:04 UTC, bluelovers commented
this fix work for cli-table2's table border

cos "─" is 2, not 1

before
---------------

┌─────────┬───────┬────────┬────────────────┐
│ address │ value │ active │ desc           │
├─────────┼───────┼────────┼────────────────┤
│ 7FEDFE  │ FF    │ false  │ 人物1 EXP 無限 │
├─────────┼───────┼────────┼────────────────┤
│ 7FF0FF  │ 90    │ false  │ p1 exp.1       │
├─────────┼───────┼────────┼────────────────┤
│ 7FF100  │ 02    │ false  │ p1 exp.2       │
├─────────┼───────┼────────┼────────────────┤
│ 7FF3FF  │ 90    │ false  │ p2 exp.1       │

after
---------------

┌─────┬────┬────┬────────┐
│ address  │ value  │ active │ desc           │
├─────┼────┼────┼────────┤
│ 7FEDFE   │ FF     │ false  │ 人物1 EXP 無限 │
├─────┼────┼────┼────────┤
│ 7FF0FF   │ 90     │ false  │ p1 exp.1       │
├─────┼────┼────┼────────┤
│ 7FF100   │ 02     │ false  │ p1 exp.2       │
├─────┼────┼────┼────────┤
│ 7FF3FF   │ 90     │ false  │ p2 exp.1       │
├─────┼────┼────┼────────┤

2017-01-09 09:37 UTC, sindresorhus commented
Please look at the diff.

2017-01-09 16:19 UTC, bluelovers commented
u mean `(0x20000 <= x && x <= 0x3fffd)` ?
this didn't make my change useless

----

```
const stringWidth = require('string-width');
console.log(stringWidth('─')); // before patch is 1, after is 2
```

2017-01-09 16:20 UTC, sindresorhus requested changes

2017-01-09 16:20 UTC, sindresorhus commented on index.js
> +	{
This is an unrelated change and should be removed.

2017-01-09 16:20 UTC, sindresorhus commented on index.js
> +	{
This is an unrelated change and should be removed.

2017-01-09 16:43 UTC, bluelovers commented
just tell me is code style not match next time, not the code is wrong lol

https://github.com/bluelovers/is-fullwidth-code-point/commit/939af8060552955bb04026eeb56f311ecd22e552

2017-01-09 16:57 UTC, sindresorhus commented
> just tell me is code style not match next time, not the code is wrong lol

I hope the next time you'll just follow the existing code style instead of wasting the time of the maintainer ;)

2017-01-09 16:57 UTC, sindresorhus commented
Can you comment some source/proof here that the unicode ranges you specified are actually fullwidth?

2017-01-09 17:03 UTC, bluelovers commented
code style is ide auto change it lol
idk how proof, but maybe u can see the url on the commit's comments

2017-01-12 15:59 UTC, sindresorhus commented
Sorry, that's not good enough. I'm not going to merge this unless I have proof that this change actually does what you say it does. It's up to you as a submitter to provide such proof.

2017-01-12 23:32 UTC, bluelovers commented
if this change patch on string-width
u will be ok or not?

2017-01-14 08:08 UTC, sindresorhus commented
> if this change patch on string-width

Can you please clarify? I don't understand what you're asking.

2017-01-26 11:26 UTC, sindresorhus commented
Closing for lack of response, test, or any kind of proof that this change is correct.

2017-01-26 11:26 UTC, closed without merging